name: QA
on: [push]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set just binary env and justfile runner
        run: |
          echo "PYRUN=uv run --extra dev" >> $GITHUB_ENV
          echo "JUSTBIN=uvx --from rust-just just" >> $GITHUB_ENV

      - name: Linting
        run: $JUSTBIN lint

      - name: Typing
        run: $JUSTBIN check
