name: QA
on: [push]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          architecture: x64

      - name: Install dependencies (and project)
        run: |
          pip install -U pip
          pip install -e .[lint,scripts,test,check]

      - name: Linting
        run: just lint

      - name: Typing
        run: just check
