name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python: ["3.13", "3.14"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set just binary env and justfile runner
        run: |
          echo "PYRUN=uv run --extra dev -p ${{matrix.python}}" >> $GITHUB_ENV
          echo "JUSTBIN=uvx --from rust-just just" >> $GITHUB_ENV

      - name: Run the tests
        run: $JUSTBIN coverage "-vvv"

      - name: Upload coverage report to codecov
        if: matrix.python == '3.12'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Ensure we can build Python targets
        run: |
          pip install -U pip build
          python3 -m build --sdist --wheel

  build_docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Ensure we can build the Docker image
        run: |
          docker build -t testimage .

      - name: Ensure we can start the Docker image
        run: |
          docker run --rm testimage
